root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/api"
bin = "tmp/main.exe"
include_ext = ["go", "yaml", "yml", "sql", "env"]
exclude_dir = ["bin", "docs", "tmp", "db"]
delay = 500
stop_on_error = true
